image: node:alpine

variables:
  STAGING_REGISTRY: www.baidu.com
  CONTAINER_DEV_IMAGE: tianrang

stages:
  - clean
  - install
  - Themis
  - docker_deploy
  - k8s_deploy

cache:
  paths:
    - node_modules/

cleanup_node_modules:
  stage: clean
  cache:
    paths:
      - node_modules/
  script:
    - rm -rf node_modules/
  when: manual

install:
  stage: install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 3 hrs
    paths:
      - node_modules/
  script:
    - yarn

deploy_doc:
  stage: docker_deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $ADMIN_USR -p $ADMIN_PWD $STAGING_REGISTRY
    - docker build -t $CONTAINER_DEV_IMAGE .
    - docker push $CONTAINER_DEV_IMAGE
  only:
    - master